
services:
    a2lix_auto_form.doctrine.metadata_factory:
        class: Doctrine\Common\Persistence\Mapping\ClassMetadataFactory
        public: false
        factory: ['@doctrine.orm.default_entity_manager', getMetadataFactory]

    a2lix_auto_form.doctrine_info:
        class: A2lix\TranslationFormBundle\ObjectInfo\DoctrineInfo
        public: false
        arguments: ['@a2lix_auto_form.doctrine.metadata_factory']

    a2lix_auto_form.default.manipulator:
        class: A2lix\TranslationFormBundle\Form\Manipulator\DefaultManipulator
        public: false
        arguments: ['@a2lix_auto_form.doctrine_info', ['id','translatable', 'locale']]

    a2lix_auto_form.default.listener.autoform:
        class: A2lix\TranslationFormBundle\Form\EventListener\AutoFormListener
        arguments: ['@a2lix_auto_form.default.manipulator']

    a2lix_auto_form.default.type.autoform:
        class: A2lix\TranslationFormBundle\Form\Type\AutoFormType
        tags:
            - { name: form.type }
        arguments: ['@a2lix_auto_form.default.listener.autoform']

    a2lix_translation_form.default.service.parameter_locale_provider:
        class: A2lix\TranslationFormBundle\Locale\DefaultProvider

    a2lix_translation_form.default.listener.translations:
        class: A2lix\TranslationFormBundle\Form\EventListener\TranslationsListener
        arguments: ['@a2lix_auto_form.default.manipulator']

    a2lix_translation_form.default.listener.translationsforms:
        class: A2lix\TranslationFormBundle\Form\EventListener\TranslationsFormsListener

    a2lix_translation_form.default.type.translations:
        class: A2lix\TranslationFormBundle\Form\Type\TranslationsType
        tags:
            - { name: form.type }
        arguments: ['@a2lix_translation_form.default.listener.translations', '@a2lix_translation_form.default.service.locale_provider']

    a2lix_translation_form.default.type.translationsforms:
        class: A2lix\TranslationFormBundle\Form\Type\TranslationsFormsType
        tags:
            - { name: form.type }
        arguments: ['@a2lix_translation_form.default.listener.translationsforms', '@a2lix_translation_form.default.service.locale_provider']

    a2lix_translation_form.default.type.translationslocalesselector:
        class: A2lix\TranslationFormBundle\Form\Type\TranslationsLocalesSelectorType
        tags:
            - { name: form.type }
        arguments: ['@a2lix_translation_form.default.service.locale_provider']

    a2lix_translation_form.default.type.translatedentity:
        class: A2lix\TranslationFormBundle\Form\Type\TranslatedEntityType
        tags:
            - { name: form.type }
        arguments: ['@request_stack']
